---
- name: Install jenkins repo
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key
  rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install jenkins
  yum: name=jenkins state=present

- name: Set jenkins service to start on boot
  service: name=jenkins enabled=true

- name: Put jenkins sysconfig
  template: src=jenkins.j2 dest=/etc/sysconfig/jenkins mode=0600
  notify: restart jenkins

- name: Install passlib for creating htpasswd
  pip: name=passlib state=latest
  when: jenkins_basic_enabled

- name: Create htpasswd
  htpasswd: path=/etc/nginx/conf.d/jenkins.htpasswd name={{ jenkins_basic_user_name }} password={{ jenkins_basic_user_password }} create=yes state=present
  when: jenkins_basic_enabled

- name: Put nginx.jenkins.conf
  template: src=nginx.jenkins.conf.j2 dest=/etc/nginx/conf.d/jenkins.conf mode=0644
  notify: restart nginx
