---
- name: Install mysql rpm
  yum: name="http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm" state="present"

- name: Install mysql
  yum: name={{ item }} state=latest
  with_items:
    - mysql-server
  notify: restart mysql

- name: Set mysql service to start on boot
  service: name=mysqld state=started enabled=true
