---
- name: Download setup shell for nodejs
  get_url: url="https://rpm.nodesource.com/setup" dest="/tmp/setup_node.sh" mode=0755

- name: Setup nodejs
  shell: /tmp/setup_node.sh

- name: Install nodejs
  yum: name=nodejs state=latest
